In [8]:
#numpy dizilerinin öğelerine ve alt dizilerine, python listelerinde de kullanılan köşeli parantez kullanılarak erişilir.

In [9]:
#TEK BOYUTLU DİZİLERDE İNDEKSLEME VE DİLİMLEME OPERASYONLARI

In [10]:
import numpy as np

In [11]:
veri = np.linspace(start=9,stop=99,num=10) #9 ve 99 dahil sayılardır.

In [12]:
veri

array([ 9., 19., 29., 39., 49., 59., 69., 79., 89., 99.])

In [13]:
veri[0] #verinin ilk elemanı

9.0

In [14]:
veri[-1] #verinin son elemanı

99.0

In [15]:
veri[2] #verinin üçüncü elemanı

29.0

In [16]:
veri[2:5] #verinin ikinci, üçüncü, dördüncü indeksteki elemanları (iki dahil beş dahil değil)

array([29., 39., 49.])

In [17]:
veri[0:6:2] #0'dan 6'ya ikişer adım şeklinde ilerleyen indekslerin elemanları (örnekte 0,2,4,6 numaralı indeksleri yazar)

array([ 9., 29., 49.])

In [18]:
#ÇOK BOYUTLU DİZİLERDE İNDEKSLEME VE DİLİMLEME OPERASYONLARI

In [19]:
veri = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [20]:
veri

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
veri.shape #3 satır 4 sütunlu

(3, 4)

In [22]:
veri[:,0] #verinin ilk sütunu

array([1, 5, 9])

In [23]:
veri[:,2] #verinin ikinci indeks sütunu

array([ 3,  7, 11])

In [24]:
veri[0,:] #verinin ilk satırı

array([1, 2, 3, 4])

In [25]:
veri[2,:] #verinin ikinci indeksteki satırı

array([ 9, 10, 11, 12])

In [35]:
veri[2,3] #verinin üçüncü satır dördüncü sütunundaki değeri

12

In [36]:
veri[0:3:2,0:4:3] #verinin 0. satırdan son indekse kadar 2 adım, 0. sütundan son indekse kadar 3 adımdaki değerleri
#yani; satırları ikişer ikişer sütunları üçer üçer ilerler.
#0. indeks ve 2. indeksteki SATIRLAR ile 0. indeks ve 3. indeksteki SÜTUNLARIN kesiştiği indekslerdeki değerlerdir.

array([[ 1,  4],
       [ 9, 12]])