In [43]:
#numpy dizisi oluşturmak için temelde iki yol vardır. bunlardan ilki numpy kütüphanesinin bize sunduğu fonksiyonları kullanarak
#bir dizi oluşturmaktır. diğeri ise pythondaki list ve tuple veri yapılarını numpy fonksiyonunda çağırarak kullanmaktır.

In [44]:
#dizi(satır,sütun) şeklinde değer verilir.

In [45]:
import numpy as np

In [46]:
#NUMPY KÜTÜPHANESİNİ KULLANARAK NUMPY DİZİSİ OLUŞTURMA

In [47]:
#zeros()
#istenilen boyut ve veri türüne göre sıfır değeri ile dolu bir dizi oluşturur
veri = np.zeros((3,2))

In [48]:
veri

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
veri.shape #veri değişkeninin boyutunu gösterir

(3, 2)

In [50]:
#ones()
#istenilen boyut ve veri türüne göre bir değeri ile dolu bir dizi oluşturur
dizi = np.ones((2,3))

In [51]:
veri

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
veri.shape

(3, 2)

In [53]:
#full()
#istenilen boyut ve veri türüne göre bir dizi veya herhangi bir sayı ile dolu bir dizi oluşturur.
#full() fonksiyonu kullanılarak, ones() ve zeros() fonk.ları ile aynı sonuca ulaşmak da mümkündür.
dizi = np.full((2,2),44)

In [54]:
dizi.shape

(2, 2)

In [55]:
#diag()
#var olan bir numpy dizisinin köşegen boyunca belirtilen değerlere sahip bir köşegen dizi oluşturur.
#kalan yerler ise sıfır ile doldurur.

In [56]:
np.diag(veri) #köşegendeki değerleri alır.

array([0., 0.])

In [57]:
np.diag(np.diag(veri)) #köşegen dışındaki verileri sıfırlar.

array([[0., 0.],
       [0., 0.]])

In [58]:
#eye()
#istenilen boyut ve veri türüne göre belirtilen köşegen boyunca bir değerleri ile bir köşegen dizisi oluşturur.
#kalan yerleri ise sıfırla doldurur.

In [59]:
veri = np.eye(3,3) #3 satır 3 sütun ile köşegen dizisi oluşturduk

In [60]:
veri

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
veri.shape

(3, 3)

In [62]:
#arange()
#istenilen başlangıç, bitiş ve artış değerleri arasında eşit aralıklı değerlere sahip bir dizi oluşturur.
veri = np.arange(start=3,stop=11,step=2) #3'ten 11'e ikişer artan bir dizi

In [63]:
veri

array([3, 5, 7, 9])

In [64]:
#linspace()
#istenilen sayıda elementle, belirtilen başlangıç ve bitiş değerleri arasında eşit aralıklı değerlere sahip dizi oluşuturur.
veri = np.linspace(start=3,stop=11,num=5) #3'ten 11'e kadar 5 değer içeren dizi

In [65]:
veri

array([ 3.,  5.,  7.,  9., 11.])

In [66]:
#random.rand()
#0 ile 1 arasında eşit olarak dağıtılan rastgele sayılarla bir dizi oluşturur.
#random.seed() fonksiyonu rastgele üretilen sayıyı sabitler.
#rastgele üretilen sayının sabitlenmesi, rastgele üretilen değerlerin her çağırdığımızda aynı sayıyı üretmesine yarar.

In [67]:
np.random.seed(0) #0 değerli sabitledik

In [68]:
veri = np.random.rand(2,3)

In [69]:
veri

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [70]:
veri.shape

(2, 3)

In [71]:
#empty()
#girdileri başlatmadan belirtilen şekil ve türde yeni bir dizi oluşturur.
#genellikle performans kritik olduğunda büyük diziler için kullanılır ve değerler daha sonra doldurulur.
veri = np.empty([2,2]) #2 satır ve 2 sütundan oluşan, rastgele değerler ile dolu biz dizi.

In [72]:
veri.shape

(2, 2)

In [73]:
#VAR OLAN PYTHON LİST VEYA TUPLE DOSYALARINI KULLANARAK NUMPY DİZİSİ OLUŞTURMA

In [74]:
#array()

In [75]:
veri=np.array([1,2,3]) #python list nesnesnden oluşan basit bir numpy dizisi
#list köşeli parantez ile gösterilir ve değerleri değişebilir özelliktedir

In [76]:
veri

array([1, 2, 3])

In [84]:
veri=np.array([[1,2],[3,4],[5,6]]) #2 python listesi içeren bir numpy dizisi

In [85]:
veri

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
veri = np.array((1,2,3)) #python tuple nesnesinden oluşan basit bir numpy dizisi
#tuple yuvarlak parantez ile gösterilir ve değerleri sabit(değişmez) özelliktedir

In [87]:
veri

array([1, 2, 3])