In [2]:
#bu fonksiyonlar, eleman olarak verilen numpy dizisine uygulandıklarında aynı boyuta sahip yeni bir dizi döndürür.
#bu fonksiyonlar, girdi dizisindeeki bütün elementlere ayrı ayrı uygulanır.

In [3]:
import numpy as np

In [4]:
a = np.array([4,16,64])

In [5]:
#exp()
#üstel hesaplar
np.exp(a)

array([5.45981500e+01, 8.88611052e+06, 6.23514908e+27])

In [6]:
#sqrt()
#karekök hesaplar
np.sqrt(a)

array([2., 4., 8.])

In [7]:
#log()
#e tabanında logaritma hesaplar
np.log(a)

array([1.38629436, 2.77258872, 4.15888308])

In [8]:
#cos()
#radyan cinsinden kosinüs hesabı yapar
np.cos(a)

array([-0.65364362, -0.95765948,  0.39185723])

In [9]:
#sin()
#radyan cinsinden sinüs hesabı yapar
np.sin(a)

array([-0.7568025 , -0.28790332,  0.92002604])

In [10]:
np.tan(a)

array([1.15782128, 0.30063224, 2.34786031])

In [ ]:
#matematiksel fonksiyonlar için math sınıfına daha ayrıntılı bakılabilir.