In [35]:
#numpy ile oluşturulan diziler homojen olmak zorundandır. homojen demek dizi içindeki bütün verilerin aynı tipte olmasıdır.
#veri tipleri tamsayılar, işaretsiz tamsayılar,mantıksal ifadeler, ondalıklı sayılar ve karmaşık sayılardır.

In [36]:
import numpy as np #eğer çalıştırmaya bu satırdan başlamazsak çalışırken "np" tanımlı değildir uyarısı alırız.

In [37]:
#TAMSAYILAR (en sık kullanılan tam sayı formları int16, int32, int64'tür)
a = np.array([100,200,300],dtype=int) #dizileri kare parentez içinde yazarız

In [38]:
a

array([100, 200, 300])

In [39]:
a.dtype

dtype('int32')

In [40]:
#İŞARETSİZ TAMSAYILAR
#eğer veri setinde negatif tamsayı içeren bir veri yoksa bu formatı kullanabiliriz
#en sık kullanılan işaretsiz tamsayı formları uint8, uint16, uint32, uint64'tür.
#bu formatı günlük hayattaki verilerimizle pek uyuşmadığı için sık kullanmayız. (özellikle görselleştirme için)

In [41]:
#MANTIKSAL İFADELER (true ve false ifadeleridir)
a = np.array([-1,0,1],dtype=bool)

In [42]:
a

array([ True, False,  True])

In [43]:
a.dtype

dtype('bool')

In [44]:
#ONDALIKLI SAYILAR
#ondalıklı sayı içeren veri setleri için kullanılır.
#en sık kullanılan işaretsiz ondalıklı sayı formları float16, float32, float64, float128'dir.
a = np.array([100,200,300],dtype=float)

In [45]:
a

array([100., 200., 300.])

In [46]:
a.dtype

dtype('float64')

In [47]:
#KARMAŞIK SAYILAR
#a + b.j şeklindeki sayılardır
a = np.array([-1,0,1],dtype=complex) #imajiner değeri belirtmediğimiz için 0 varsayılan değerini alır.

In [48]:
a.real #a dizisindeki ifadelerin gerçek kısımları

array([-1.,  0.,  1.])

In [49]:
a.imag# a dizisindeki ifadelerin sanal(imajiner) kısımları

array([0., 0., 0.])

In [50]:
a

array([-1.+0.j,  0.+0.j,  1.+0.j])

In [51]:
a.dtype

dtype('complex128')