In [1]:
#numpy dizileriyle yapılan temel aritmetik işlemler eleman bazlı işlemler gerçekleştirir.

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [4]:
c = a+b #a ve b dizileri toplanarak yeni bir c dizisi oluşturulmuştur.

In [5]:
c

array([11, 22, 33])

In [6]:
c = a-b 

In [7]:
c

array([ -9, -18, -27])

In [8]:
c = a*b 

In [9]:
c

array([10, 40, 90])

In [10]:
c = a/b 

In [11]:
c

array([0.1, 0.1, 0.1])