In [2]:
#koşullu ifadeler bize verileri yönetmek ve seçmek konusunda yardımcı olur.

In [3]:
import numpy as np

In [13]:
a = np.array([[2,4,6],[20,40,60]])
b = np.array([[1,3,5],[10,30,50]])

In [5]:
a

array([[ 2,  4,  6],
       [20, 40, 60]])

In [6]:
b

array([[ 1,  3,  5],
       [10, 30, 50]])

In [16]:
#argwhere()
#koşulu sağlayan değerlerin indekini verir. çıktı, [satır,sütun] şeklinde olur.
np.argwhere(a>15)

array([[1, 0],
       [1, 1],
       [1, 2]], dtype=int64)

In [17]:
#where()
#koşulu sağlayan değerleri değiştirme imkanı tanır.
#ilk parametre koşul; ikincisi koşul doğruysa verinin çekileceği değer,sonuncusu koşul yanlışsa verinin çekileceği değerdir.
np.where(a>5,0,a)

array([[2, 4, 0],
       [0, 0, 0]])

In [18]:
#a verisinin 4'e tam bölünen değerlerini b verisindeki aynı konumundaki değeri ile doldurulmasını yapalım:
np.where(a%4,b,a)

array([[ 1,  4,  5],
       [20, 40, 60]])

In [22]:
#select()
#koşullar listesine bağlı olarak bir dizi listesinden eğer seçer. where'den farklı olarak birden fazla koşulu işleyebilir.
sartlar=[a<10,a>10]
durumlar=[0,1]
np.select(sartlar,durumlar)

array([[0, 0, 0],
       [1, 1, 1]])