In [1]:
### verilerle çalışırken numpy dizilerini yeniden düzenlemek ve şeklini değiştirmek önemlidir.
#numpy kütüphanesinin bu manipülalasyonlar için zengin bir fonksiyon listesi vardır.

In [2]:
import numpy as np

In [3]:
#append()
#numpy dizisine yeni eleman ekler ve yeni bir numpy dizisi oluşturur.

In [4]:
veri = np.array([1,2,3])

In [5]:
veri

array([1, 2, 3])

In [6]:
yeniVeri = np.append(veri,[4,5])

In [7]:
yeniVeri

array([1, 2, 3, 4, 5])

In [8]:
#delete()
#numpy dizisinde belirli bir konumdaki bir öğeyi indeks bilgisi ile siler.

In [9]:
yeniVeri = np.delete(veri,0)

In [10]:
yeniVeri

array([2, 3])

In [11]:
#ndarray.transpose()
#numpy dizisinin transpozunu alır. transpozunu almak, satır ile sütunların yer değiştirmesidir.

In [13]:
veri = np.array([[1,2,3],[4,5,6]])

In [14]:
veri

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
veri.shape #2 satır 3 sütun

(2, 3)

In [16]:
yeniVeri = np.ndarray.transpose(veri)

In [17]:
yeniVeri

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
yeniVeri.shape

(3, 2)

In [19]:
#ndarray.reshape()
#bir numpy dizisinin elemanlarını değiştirmeden boyutunu değiştirir.

In [20]:
veri = np.array([1,2,3,4,5,6])

In [21]:
veri

array([1, 2, 3, 4, 5, 6])

In [22]:
veri.shape #1 satır 6 sütun

(6,)

In [23]:
yeniVeri = np.ndarray.reshape(veri,(2,3))

In [24]:
yeniVeri

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
yeniVeri.shape #2 satır 3 sütun

(2, 3)

In [26]:
yeniVeri = np.ndarray.reshape(yeniVeri,(6,1))

In [27]:
yeniVeri

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [28]:
yeniVeri.shape #6 satır 1 sütun

(6, 1)

In [29]:
#ndarray.flatten()
#bir numpy dizisini tek boyuta indirger. ndarray.reshape() fonksiyonunun özel bir hali gibidir.

In [30]:
veri = np.array([[1,2,3],[4,5,6]])

In [31]:
veri

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
yeniVeri = np.ndarray.flatten(veri)

In [33]:
yeniVeri

array([1, 2, 3, 4, 5, 6])

In [34]:
#concatenate()
#belli bir eksen boyunca dizileri birbiri ardına ekleyerek yeni bir dizi oluşturur

In [35]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [36]:
a

array([[1, 2],
       [3, 4]])

In [37]:
b

array([[5, 6],
       [7, 8]])

In [38]:
c = np.concatenate((a,b),axis=0)
d = np.concatenate((a,b),axis=1)

In [39]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [41]:
#vstack()
#dikey olarak numpy dizilerini yığınlar. dizileri  alt alta birleştirir.

In [66]:
#dizileri alt alta birleştireceği için dizilerin sütun sayıları aynı olmalıdır.
a = np.array([[1,2,3],[5,6,7]])
b = np.array([10,20,30])

In [67]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [68]:
b

array([10, 20, 30])

In [69]:
c = np.vstack((a,b))

In [70]:
c

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [10, 20, 30]])

In [71]:
#hstack()
#yatay olarak dizileri yığınlar. dizileri yan yana birleştirir.

In [72]:
#dizileri yan yana birleştireceğinden dizilerin satır sayıları aynı olmalıdır.
a = np.array([1,2,3,4])
b = np.array([10,20,30])

In [73]:
a

array([1, 2, 3, 4])

In [74]:
b

array([10, 20, 30])

In [76]:
c = np.hstack((a,b))

In [77]:
c

array([ 1,  2,  3,  4, 10, 20, 30])